envs:
- KEYSTORE_PATH: $BITRISE_SOURCE_DIR/android/secure/bitrisefastlane-key.keystore
- KEYSTORE_PASSWORD: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD
- KEYSTORE_ALIAS: $BITRISEIO_ANDROID_KEYSTORE_ALIAS
- GOOGLE_JSON_SECRET_FILE: $BITRISE_SOURCE_DIR/android/secure/api-5304109077874397815-340283-e60e96c8a3d0.json
