envs:
  - FASTLANE_USER: matthew.jinkens@gmail.com
  - FASTLANE_PASSWORD: 02469785Mj
  - MATCH_PASSWORD: 02469785Mj
  - FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: hxav-gejv-cifh-flig
  - SSH_RSA_PRIVATE_KEY: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2wC2Yd8uQif2sEuFrWiRp9iqAfKF9vfY0V1xvWrGiZpniMkvLslLbjb/BxfpqZgINovui0DLAKiQKstrOV9Ud6H9Gf+UVkIjB36uZvQO3ryCDTFewwW/pUdDFmA1QwtlviHXIM9jJLh7prFvyNOAKJ+YjCXAKXFZXF6ZXB6xSJz0QZTmTmQRcGRYPUP09yenLrLT0vBc1rYgyV+Am9uD2Mvp4GULCFrU0ewtKUWVHwoQLFGwldCwePLa20T+6NoOAjIfa64QIv0x8L7M2fWgoqJVoNnkr3tz5GpDPSbjEKIezQojmu230efoEkMibCJ6T6+lfZG55hvpbZyUm5vm9 builds@bitrise.io'
