# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: is_ci)
    increment_build_number
    commit_version_bump(
        message: "Fastlane iOS bump build number to #{lane_context[SharedValues::BUILD_NUMBER]} [ci skip]",
        xcodeproj: "./BitriseFastlane.xcodeproj",
        force: true
    )
    cocoapods(clean_install: true)
    build_app(workspace: "BitriseFastlane.xcworkspace", scheme: "BitriseFastlane", configuration: "Release")
    upload_to_testflight(skip_waiting_for_build_processing: true)
    clean_build_artifacts
  end
end
