# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Alpha Build to the Google Play Store"
  lane :alpha do
    build_number = increment_version_code(
        gradle_file_path: "./app/build.gradle"
    )
    gradle(task: "clean assembleRelease")
    puts "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    supply(
        track: "alpha",
        apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    )
    git_commit(
        path: "./app/build.gradle",
        message: "Fastlane Android bump build number to #{build_number} [ci skip]",
    )
    slack_upload_title = "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}".split("outputs/apk/release/")[1]
    slack_file_path = "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    slack_comment = "@here [QA-Staging] New Android APK available for Bitrise Fastlane  🛠 ➡ 📱"
    slack_upload(
        slack_api_token: ENV["SLACK_API_TOKEN"],
        channel: "#mobile-deployments",
        title: slack_upload_title,
        file_path: slack_file_path,
        initial_comment: slack_comment
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
